#------------------------------------------------------------------------------
# Installs NodeJS, which is needed for running the Linux ITs.
#
# Build from the basedir:
#   docker build -f it/docker/Dockerfile_17 -t sonar-scanner-cli-qa-17 it/docker
#
# Verify the content of the image by running a shell session in it:
#   docker run -it sonar-scanner-cli-qa bash
#
# CirrusCI builds the image when needed. No need to manually upload it.
#------------------------------------------------------------------------------

FROM 166916561812.dkr.ecr.eu-central-1.amazonaws.com/base:j17-m3-latest

USER root

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs

USER sonarsource
